
-- Drop Existing Tables--
DROP TABLE IF EXISTS W_ERROR_LOG CASCADE;
DROP TABLE IF EXISTS W_JOB_CHANGE_Data CASCADE;
DROP TABLE IF EXISTS W_JOB_F CASCADE;
DROP TABLE IF EXISTS W_LEAD_F CASCADE;
DROP TABLE IF EXISTS W_LOCATION_D CASCADE;
DROP TABLE IF EXISTS W_TIME_D CASCADE;
DROP TABLE IF EXISTS W_SALES_CLASS_D CASCADE;
DROP TABLE IF EXISTS W_SALES_AGENT_D CASCADE;
DROP TABLE IF EXISTS W_CUSTOMER_D CASCADE;
DROP TABLE IF EXISTS W_MACHINE_TYPE_D CASCADE;
DROP TABLE IF EXISTS W_CUST_LOCATION_D CASCADE;
DROP TABLE IF EXISTS W_SUB_JOB_F CASCADE;
DROP TABLE IF EXISTS W_JOB_SHIPMENT_F CASCADE;
DROP TABLE IF EXISTS W_INVOICELINE_F CASCADE;
DROP TABLE IF EXISTS W_FINANCIAL_SUMMARY_SALES_F CASCADE;
DROP TABLE IF EXISTS W_FINANCIAL_SUMMARY_COST_F CASCADE;

--Drop Existing Sequences--
DROP SEQUENCE IF EXISTS W_CUST_SEQ;
DROP SEQUENCE IF EXISTS W_SALESAGENT_SEQ;
DROP SEQUENCE IF EXISTS W_SALESCLASS_SEQ;
DROP SEQUENCE IF EXISTS W_LOCATION_SEQ;
DROP SEQUENCE IF EXISTS W_LEAD_SEQ;
DROP SEQUENCE IF EXISTS W_JOB_SEQ;
DROP SEQUENCE IF EXISTS W_ERROR_LOG_SEQ;

-- CREATE SEQUENCE values starting with 1
CREATE SEQUENCE W_CUST_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE W_SALESAGENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE W_SALESCLASS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE W_LOCATION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE W_LEAD_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE W_JOB_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE W_ERROR_LOG_SEQ;

-- Create Tables--
/*********************************
        W_CUSTOMER_D
**********************************/
CREATE TABLE W_CUSTOMER_D
(	CUST_KEY		INTEGER,
	CUST_NAME		VARCHAR(50) NOT NULL,
	CITY			VARCHAR(25)	NOT NULL,
	COUNTRY			VARCHAR(25)	NOT NULL,
	CREDIT_LIMIT	DECIMAL(10,2) NOT NULL,
	E_MAIL_ADDRESS	VARCHAR(50)	NOT NULL,
	CUST_STATE		VARCHAR(2)	NOT NULL,
	ZIP				VARCHAR(10)	NOT NULL,
	TERMS_CODE		VARCHAR(10)	NOT NULL,
	CONSTRAINT W_CUSTOMER_D_PK PRIMARY KEY (CUST_KEY)	
);

/*********************************
        W_SALES_AGENT
**********************************/ 
CREATE TABLE W_SALES_AGENT_D
(	SALES_AGENT_ID		INTEGER,
	SALES_AGENT_NAME	VARCHAR(60)	NOT NULL,
	SALES_AGENT_STATE	VARCHAR(2)	NOT NULL,
	COUNTRY				VARCHAR(25)	NOT NULL ,
	CONSTRAINT W_SALES_AGENT_D_PK PRIMARY KEY (SALES_AGENT_ID)
);

/*********************************
        W_SALES_CLASS_D
**********************************/
CREATE TABLE W_SALES_CLASS_D
(	SALES_CLASS_ID		INTEGER,
	SALES_CLASS_DESC	VARCHAR(250) NOT NULL,
	BASE_PRICE			DECIMAL(8,4) NOT NULL,
	CONSTRAINT W_SALES_CLASS_D_PK PRIMARY KEY (SALES_CLASS_ID)	
);

/*********************************
        W_TIME_D
**********************************/ 
CREATE TABLE W_TIME_D
(	TIME_ID			INTEGER	NOT NULL,
	TIME_YEAR		INTEGER	NOT NULL,
	TIME_QUARTER	INTEGER	NOT NULL,
	TIME_MONTH		INTEGER	NOT NULL,
	TIME_DAY		INTEGER	NOT NULL,
	TIME_WEEK		INTEGER	NOT NULL,
	CONSTRAINT W_TIME_D_PK PRIMARY KEY (TIME_ID),
	CONSTRAINT W_TIME_D_UNIQUEGOUP1 UNIQUE (TIME_YEAR, TIME_MONTH, TIME_DAY) 
);

/*********************************
        W_LOCATION_D
**********************************/ 
CREATE TABLE W_LOCATION_D
(	LOCATION_ID		INTEGER,
	LOCATION_NAME	VARCHAR(50)	NOT NULL,
	constraint w_location_d_pk primary key (location_id), 
	constraint w_location_unique1 unique (location_name)
);

/*********************************
        W_LEAD_F
**********************************/ 
CREATE TABLE W_LEAD_F
(	LEAD_ID			INTEGER,
	QUOTE_QTY		INTEGER NOT NULL,
	QUOTE_PRICE		DECIMAL(11,2) NOT NULL,
	LEAD_SUCCESS	VARCHAR(1)	NOT NULL,
	JOB_ID			INTEGER,
	CREATED_DATE	INTEGER NOT NULL,
	CUST_ID			INTEGER NOT NULL,
	LOCATION_ID		INTEGER NOT NULL,
	SALES_AGENT_ID	INTEGER NOT NULL,
	SALES_CLASS_ID	INTEGER NOT NULL,
	CONSTRAINT W_LEAD_F_PK PRIMARY KEY (LEAD_ID),
	CONSTRAINT W_LEAD_CREATED_DATE_FK FOREIGN KEY (CREATED_DATE) REFERENCES W_TIME_D (TIME_ID),
	CONSTRAINT W_LEAD_CUST_ID_FK FOREIGN KEY (CUST_ID) REFERENCES W_CUSTOMER_D (CUST_KEY),
	CONSTRAINT W_LEAD_LOCATION_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES W_LOCATION_D (LOCATION_ID),
	CONSTRAINT W_LEAD_SALES_AGENT_ID_FK FOREIGN KEY (SALES_AGENT_ID) REFERENCES W_SALES_AGENT_D (SALES_AGENT_ID),
	CONSTRAINT W_LEAD_SALES_CLASS_ID_FK FOREIGN KEY (SALES_CLASS_ID) REFERENCES W_SALES_CLASS_D (SALES_CLASS_ID)
);

/*********************************
        W_JOB_F
**********************************/ 
CREATE TABLE W_JOB_F
(	JOB_ID				INTEGER,
	CONTRACT_DATE		INTEGER	NOT NULL,
	SALES_AGENT_ID		INTEGER	NOT NULL,
	SALES_CLASS_ID		INTEGER NOT NULL,
	LOCATION_ID			INTEGER	NOT NULL,
	CUST_ID_ORDERED_BY	INTEGER	NOT NULL,
	DATE_PROMISED		INTEGER,
	DATE_SHIP_BY		INTEGER,
	NUMBER_OF_SUBJOBS	INTEGER	NOT NULL,
	UNIT_PRICE			DECIMAL(6,2) NOT NULL,
	QUANTITY_ORDERED	INTEGER NOT NULL,
	QUOTE_QTY			INTEGER NOT NULL,
	CONSTRAINT W_JOB_F_PK PRIMARY KEY (JOB_ID),
	CONSTRAINT W_JOB_CONTRACT_DATE_FK FOREIGN KEY (CONTRACT_DATE) REFERENCES W_TIME_D (TIME_ID),
	CONSTRAINT W_JOB_SALES_AGENT_FK FOREIGN KEY (SALES_AGENT_ID) REFERENCES W_SALES_AGENT_D (SALES_AGENT_ID),
	CONSTRAINT W_JOB_SALES_CLASS_FK FOREIGN KEY (SALES_CLASS_ID) REFERENCES W_SALES_CLASS_D (SALES_CLASS_ID),
	CONSTRAINT W_JOB_LOCATION_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES W_LOCATION_D (LOCATION_ID),
	CONSTRAINT W_JOB_CUST_ID_ORDER_BY_FK FOREIGN KEY (CUST_ID_ORDERED_BY) REFERENCES W_CUSTOMER_D (CUST_KEY),
	CONSTRAINT W_JOB_DATE_PROMISED_FK FOREIGN KEY (DATE_PROMISED) REFERENCES W_TIME_D (TIME_ID),
	CONSTRAINT W_JOB_DATE_SHIP_BY_FK FOREIGN KEY (DATE_SHIP_BY) REFERENCES W_TIME_D	(TIME_ID)
);

/*********************************
        UNKNOWN TABLES
**********************************/ 
CREATE TABLE W_MACHINE_TYPE_D
( MACHINE_TYPE_ID INTEGER,
  MANUFACTURER VARCHAR(100) NOT NULL,
  MACHINE_MODEL VARCHAR(100) NOT NULL,
  RATE_PER_HOUR INTEGER NOT NULL,
  NUMBER_OF_MACHINES INTEGER NOT NULL,
	CONSTRAINT W_MACHINE_TYPE_D_PK PRIMARY KEY (MACHINE_TYPE_ID)
);

CREATE TABLE W_CUST_LOCATION_D
( CUST_LOC_KEY INTEGER,
  CITY VARCHAR(100) NOT NULL,
  COUNTRY VARCHAR(50) NOT NULL,
  CREDIT_LIMIT INTEGER NOT NULL,
  E_MAIL_ADDRESS VARCHAR(100) NOT NULL,
  CUST_LOCATION_STATE VARCHAR(20) NOT NULL,
  ZIP VARCHAR(20) NOT NULL,
  CUST_KEY INTEGER NOT NULL,
  CUST_NAME VARCHAR(100) NOT NULL,
	CONSTRAINT W_CUST_LOCATION_D_PK PRIMARY KEY (CUST_LOC_KEY),
	CONSTRAINT W_CUST_LOCATION_CUST_KEY_FK FOREIGN KEY (CUST_KEY) REFERENCES W_CUSTOMER_D (CUST_KEY)
);

CREATE TABLE W_SUB_JOB_F
( SUB_JOB_ID INTEGER NOT NULL,
	COST_LABOR DECIMAL(6,2),
  COST_MATERIAL DECIMAL(6,2),
  COST_OVERHEAD DECIMAL(6,2),
  MACHINE_HOURS INTEGER NOT NULL,
  QUANTITY_PRODUCED INTEGER NOT NULL,
  SUB_JOB_AMOUNT INTEGER NOT NULL,
  JOB_ID INTEGER NOT NULL,
  MACHINE_TYPE_ID INTEGER NOT NULL,
  SALES_CLASS_ID INTEGER NOT NULL,
  DATE_PROD_BEGIN INTEGER NOT NULL,
  DATE_PROD_END INTEGER NOT NULL,
  LOCATION_ID INTEGER NOT NULL,
  CUST_ID_ORDERED_BY INTEGER NOT NULL,
	CONSTRAINT W_SUB_JOB_F_PK PRIMARY KEY (SUB_JOB_ID),
	CONSTRAINT W_SUB_JOB_JOB_FK FOREIGN KEY (JOB_ID) REFERENCES W_JOB_F (JOB_ID),
	CONSTRAINT W_SUB_JOB_MACHINE_TYPE_FK FOREIGN KEY (MACHINE_TYPE_ID) REFERENCES W_MACHINE_TYPE_D (MACHINE_TYPE_ID),
	CONSTRAINT W_SUB_JOB_SALES_CLASS_FK FOREIGN KEY (SALES_CLASS_ID) REFERENCES W_SALES_CLASS_D (SALES_CLASS_ID),
	CONSTRAINT W_SUB_JOB_DATE_PROD_BEGIN_FK FOREIGN KEY (DATE_PROD_BEGIN) REFERENCES W_TIME_D (TIME_ID),
	CONSTRAINT W_SUB_JOB_DATE_PROD_END_FK FOREIGN KEY (DATE_PROD_END) REFERENCES W_TIME_D (TIME_ID),
	CONSTRAINT W_SUB_JOB_LOCATION_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES W_LOCATION_D (LOCATION_ID),
	CONSTRAINT W_SUB_JOB_CUST_ID_ORDERED_BY_FK FOREIGN KEY (CUST_ID_ORDERED_BY) REFERENCES W_CUSTOMER_D (CUST_KEY)
);

CREATE TABLE W_INVOICELINE_F
( INVOICE_ID INTEGER NOT NULL,
  INVOICE_QUANTITY INTEGER NOT NULL,
  INVOICE_AMOUNT INTEGER NOT NULL,
  QUANTITY_SHIPPED INTEGER NOT NULL,
  SALES_CLASS_ID INTEGER NOT NULL,
  INVOICE_SENT_DATE INTEGER NOT NULL,
  INVOICE_DUE_DATE INTEGER NOT NULL,
  CUST_KEY INTEGER NOT NULL,
  SALES_AGENT_ID INTEGER NOT NULL,
  LOCATION_ID INTEGER NOT NULL,
	CONSTRAINT W_INVOICELINE_F_PK PRIMARY KEY (INVOICE_ID),
	CONSTRAINT W_INVOICELINE_SALES_CLASS_FK FOREIGN KEY (SALES_CLASS_ID) REFERENCES W_SALES_CLASS_D (SALES_CLASS_ID),
	CONSTRAINT W_INVOICELINE_INVOICE_SENT_DATE_FK FOREIGN KEY (INVOICE_SENT_DATE) REFERENCES W_TIME_D (TIME_ID),
	CONSTRAINT W_INVOICELINE_INVOICE_DUE_DATE_FK FOREIGN KEY (INVOICE_DUE_DATE) REFERENCES W_TIME_D (TIME_ID),
	CONSTRAINT W_INVOICELINE_CUST_KEY_FK FOREIGN KEY (CUST_KEY) REFERENCES W_CUSTOMER_D (CUST_KEY),
	CONSTRAINT W_INVOICELINE_SALES_AGENT_FK FOREIGN KEY (SALES_AGENT_ID) REFERENCES W_SALES_AGENT_D (SALES_AGENT_ID),
	CONSTRAINT W_INVOICELINE_LOCATION_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES W_LOCATION_D (LOCATION_ID)
);

CREATE TABLE W_JOB_SHIPMENT_F
( JOB_SHIPMENT_ID INTEGER NOT NULL,
  ACTUAL_QUANTITY INTEGER NOT NULL,
  REQUESTED_QUANTITY INTEGER NOT NULL,
  BOXES INTEGER NOT NULL,
  QUANTITY_PER_BOX INTEGER NOT NULL,
  QUANTITY_PER_PARTIAL_BOX INTEGER NOT NULL,
  SHIPPED_AMOUNT INTEGER NOT NULL,
  SUB_JOB_ID INTEGER NOT NULL,
  SALES_CLASS_ID INTEGER NOT NULL,
  LOCATION_ID INTEGER NOT NULL,
  CUST_ID_SHIP_TO INTEGER NOT NULL,
  ACTUAL_SHIP_DATE INTEGER NOT NULL,
  REQUESTED_SHIP_DATE INTEGER NOT NULL,
  INVOICE_ID INTEGER,
	CONSTRAINT W_JOB_SHIPMENT_PK PRIMARY KEY (JOB_SHIPMENT_ID),
	CONSTRAINT W_JOB_SHIPMENT_SUB_JOB_FK FOREIGN KEY (SUB_JOB_ID) REFERENCES W_SUB_JOB_F (SUB_JOB_ID),
	CONSTRAINT W_JOB_SHIPMENT_SALES_CLASS_FK FOREIGN KEY (SALES_CLASS_ID) REFERENCES W_SALES_CLASS_D (SALES_CLASS_ID),
	CONSTRAINT W_JOB_SHIPMENT_LOCATION_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES W_LOCATION_D (LOCATION_ID),
	CONSTRAINT W_JOB_SHIPMENT_CUST_ID_SHIP_TO_FK FOREIGN KEY (CUST_ID_SHIP_TO) REFERENCES W_CUST_LOCATION_D (CUST_LOC_KEY),
	CONSTRAINT W_JOB_SHIPMENT_ACTUAL_SHIP_DATE_FK FOREIGN KEY (ACTUAL_SHIP_DATE) REFERENCES W_TIME_D (TIME_ID),
	CONSTRAINT W_JOB_SHIPMENT_REQUESTED_SHIP_DATE_FK FOREIGN KEY (REQUESTED_SHIP_DATE) REFERENCES W_TIME_D (TIME_ID),
	CONSTRAINT W_JOB_SHIPMENT_INVOICE_FK FOREIGN KEY (INVOICE_ID) REFERENCES W_INVOICELINE_F (INVOICE_ID)
);

CREATE TABLE W_FINANCIAL_SUMMARY_SALES_F
( FINANCIAL_SUMMARY_SALES_ID INTEGER NOT NULL,
  ACTUAL_UNITS INTEGER NOT NULL,
  ACTUAL_AMOUNT DECIMAL(6,2),
  FORCAST_UNIT INTEGER NOT NULL,
  FORCAST_AMOUNT INTEGER NOT NULL,
  LOCATION_ID INTEGER NOT NULL,
  SALES_CLASS_ID INTEGER NOT NULL,
  REPORT_BEGIN_DATE_ID INTEGER NOT NULL,
  REPORT_END_DATE_ID INTEGER NOT NULL,
	CONSTRAINT W_FINANCIAL_SUMMARY_SALES_F_PK PRIMARY KEY (FINANCIAL_SUMMARY_SALES_ID),
	CONSTRAINT W_FINANCIAL_SUMMARY_SALES_LOCATION_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES W_LOCATION_D (LOCATION_ID),
	CONSTRAINT W_FINANCIAL_SUMMARY_SALES_SALES_CLASS_FK FOREIGN KEY (SALES_CLASS_ID) REFERENCES W_SALES_CLASS_D (SALES_CLASS_ID),
	CONSTRAINT W_FINANCIAL_SUMMARY_SALES_REPORT_BEGIN_DATE_FK FOREIGN KEY (REPORT_BEGIN_DATE_ID) REFERENCES W_TIME_D (TIME_ID),
	CONSTRAINT W_FINANCIAL_SUMMARY_SALES_REPORT_END_DATE_FK FOREIGN KEY (REPORT_END_DATE_ID) REFERENCES W_TIME_D (TIME_ID)
);

CREATE TABLE W_FINANCIAL_SUMMARY_COST_F
( FINANCIAL_SUMMARY_COST_ID INTEGER NOT NULL,
  ACTUAL_UNITS INTEGER NOT NULL,
  ACTUAL_LABOR_COST INTEGER NOT NULL,
  ACTUAL_MATERIAL_COST DECIMAL(6,2),
  ACTUAL_MACHINE_COST INTEGER NOT NULL,
  ACTUAL_OVERHEAD_COST DECIMAL(6,2),
  BUDGET_UNITS INTEGER NOT NULL,
  BUDGET_LABOR_COST INTEGER NOT NULL,
  BUDGET_MATERIAL_COST DECIMAL(6,2),
  BUDGET_MACHINE_COST INTEGER NOT NULL,
  BUDGET_OVERHEAD_COST DECIMAL(6,2),
  LOCATION_ID INTEGER NOT NULL,
  MACHINE_TYPE_ID INTEGER NOT NULL,
  SALES_CLASS_ID INTEGER NOT NULL,
  REPORT_BEGIN_DATE_ID INTEGER NOT NULL,
  REPORT_END_DATE_ID INTEGER NOT NULL,
	CONSTRAINT W_FINANCIAL_SUMMARY_COST_F_PK PRIMARY KEY (FINANCIAL_SUMMARY_COST_ID),
	CONSTRAINT W_FINANCIAL_SUMMARY_COST_LOCATION_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES W_LOCATION_D (LOCATION_ID),
	CONSTRAINT W_FINANCIAL_SUMMARY_COST_MACHINE_TYPE_ID_FK FOREIGN KEY (MACHINE_TYPE_ID) REFERENCES W_MACHINE_TYPE_D (MACHINE_TYPE_ID),
	CONSTRAINT W_FINANCIAL_SUMMARY_COST_SALES_CLASS_ID_FK FOREIGN KEY (SALES_CLASS_ID) REFERENCES W_SALES_CLASS_D (SALES_CLASS_ID),
	CONSTRAINT W_FINANCIAL_SUMMARY_COST_REPORT_BEGIN_DATE_ID_FK FOREIGN KEY (REPORT_BEGIN_DATE_ID) REFERENCES W_TIME_D (TIME_ID),
	CONSTRAINT W_FINANCIAL_SUMMARY_COST_REPORT_END_DATE_ID_FK FOREIGN KEY (REPORT_END_DATE_ID) REFERENCES W_TIME_D (TIME_ID)
);

/*********************************
    W_JOB_CHANGE_DATA
**********************************/
CREATE TABLE W_JOB_CHANGE_DATA
(	CHANGE_ID			INTEGER NOT NULL,
	CONTRACT_DATE		CHAR(10),
	SALES_AGENT_ID		INTEGER,
	SALES_CLASS_ID		INTEGER,
	LOCATION_ID			INTEGER,
	CUST_ID_ORDERED_BY	INTEGER,
	DATE_PROMISED		CHAR(10),
	DATE_SHIP_BY		CHAR(10),
	NUMBER_OF_SUBJOBS	INTEGER,
	UNIT_PRICE			DECIMAL(6,2),
	QUANTITY_ORDERED	INTEGER,
	QUOTE_QTY			INTEGER,
	LEAD_ID				INTEGER,
	CONSTRAINT W_JOB_CHANGE_DATA_PK PRIMARY KEY (CHANGE_ID)		
);

/*********************************
    W_ERROR_LOG
**********************************/
CREATE TABLE W_ERROR_LOG 
(	LOG_ID		INTEGER NOT NULL,
	CHANGE_ID	INTEGER,
	JOB_ID		INTEGER,
	NOTE		VARCHAR(200),
	CONSTRAINT W_ERROR_LOG_PK PRIMARY KEY (LOG_ID),
	CONSTRAINT W_ERROR_LOG_CHANGE_ID_FK FOREIGN KEY(CHANGE_ID) REFERENCES W_JOB_CHANGE_DATA (CHANGE_ID)
);

COMMIT;
